sonar.projectKey=ragilhadi_qwik
sonar.organization=ragilhadi
sonar.projectName=qwik

sonar.sources=qwik
sonar.tests=tests
sonar.language=py
sonar.python.version=3.12

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/__pycache__/**,**/*.pyc
